### ISSUE TITLE
Missing ref and query files aborts with error rather than a good error message

### ISSUE THREAD

**Issue by mooreryan** [mooreryan/group_proteins#15]
## Examples

Missing queries.

```
$ ./pasv -o arositen
Traceback (most recent call last):
	2: from ./pasv:111:in `<main>'
	1: from /Users/moorer/.rvm/gems/ruby-2.6.0@pasv/gems/abort_if-0.2.0/lib/abort_if.rb:109:in `abort_unless_file_exists'
/Users/moorer/.rvm/gems/ruby-2.6.0@pasv/gems/abort_if-0.2.0/lib/abort_if.rb:109:in `exists?': no implicit conversion of nil into String (TypeError)
```

Missing refs

```
$ ./pasv -o arositen -q test_files/queries.fa
Traceback (most recent call last):
	2: from ./pasv:112:in `<main>'
	1: from /Users/moorer/.rvm/gems/ruby-2.6.0@pasv/gems/abort_if-0.2.0/lib/abort_if.rb:109:in `abort_unless_file_exists'
/Users/moorer/.rvm/gems/ruby-2.6.0@pasv/gems/abort_if-0.2.0/lib/abort_if.rb:109:in `exists?': no implicit conversion of nil into String (TypeError)
```

Technically this is a bug in `abort_if`'s `abort_unless_file_exists` function.

## Solution

- [x] Check if query and ref files are actually given
- [x] Check that they both exist

**Comment by mooreryan** [comment]
Done
